-- Give user some feedback

SET termout ON
prompt Clearing database.
SET termout OFF
SET feedback ON

-- Remove any existing tables

DROP TABLE Party CASCADE CONSTRAINTS;
DROP TABLE Client CASCADE CONSTRAINTS;
DROP TABLE Employee CASCADE CONSTRAINTS;
DROP TABLE Claimant CASCADE CONSTRAINTS;
DROP TABLE Policy CASCADE CONSTRAINTS;
DROP TABLE Holds CASCADE CONSTRAINTS;
DROP TABLE UnderWritingAction CASCADE CONSTRAINTS;
DROP TABLE CoveredItem CASCADE CONSTRAINTS;
DROP TABLE Coverage CASCADE CONSTRAINTS;
DROP TABLE Covers CASCADE CONSTRAINTS;
DROP TABLE RatingAction CASCADE CONSTRAINTS;
DROP TABLE Claim CASCADE CONSTRAINTS;
DROP TABLE ClaimAction CASCADE CONSTRAINTS;